services:
  mysql:
    image: mysql:8.4
    container_name: ecommerce-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ecommerce_api
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: change-me
      MYSQL_ROOT_PASSWORD: root-change-me
    ports:
      - "3306:3306"
    volumes:
      - ecommerce_mysql_data:/var/lib/mysql

volumes:
  ecommerce_mysql_data:
